spring:
  datasource:
    url: jdbc:postgresql://localhost:13551/itvdn
    username: itvdn
    password: secret
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db-changelog.xml

  docker:
    compose:
      skip:
        in-tests: false
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
